myNextApplication:
  component: '@sls-next/serverless-component@latest'
  inputs:
    name:
      defaultLambda: GloomyLambda
      imageLambda: GloomyImageLambda
    bucketRegion: 'ap-northeast-2'
    cloudfront:
      comment: 'next deploy'